[package]
name = "rust_nbody_50D"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
rand = "0.8.5"
rand_distr = "0.4.3"
postgres = "0.19.7"
plotters = "0.3.5"
wgpu = "22.0"
bytemuck = { version = "1.16", features = ["derive"] }
pollster = "0.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
